const theme = {
  'heading-color': '#333333',
  'primary-color': '#3954FF',
  'link-color': '#3954FF',
  'border-color-base': '#EBEEF9',
  'layout-body-background': '#f5f8fc',
  'breadcrumb-link-color-hover': '#3954FF',
  'primary-1': '#f5f7fa',
  'border-radius-base': '4px',
  'border-radius-sm': '2px',
  'btn-default-border': '#CBCFE3',
  'btn-default-color': '#333333',
  'table-header-bg': '#EFF3F9',
  'table-header-color': '#606266',
  'table-border-radius-base': '0',
  'input-color': '#333333',
  'input-border-color': '#EBEEF9',
  'input-height-base': '28px',
  'input-height-lg': '36px',
  'input-placeholder-color': '#c0c4cc',
  'btn-height-base': '36px',
  'btn-height-sm': '32px',
  'tag-font-size': '14px',
  'switch-height': '24px',
  'tree-title-height': '30px',
  'tree-directory-selected-color': '#3954FF',
  'tree-directory-selected-bg': '#F1F5FF',
  'menu-dark-bg': '#19202C',
  'menu-dark-item-active-bg': '#3954FF',
  'layout-header-background': '#19202C',
  'layout-header-height': '50px',
  'layout-header-padding': '0 20px',
  'tabs-hover-color': '#3954FF',
  'tabs-active-color': '#3954FF',
  'popover-color': '#333333',
  'menu-item-color': '#333333',
  'disabled-color': '#BFC4CD',
  'disabled-bg': '#FBFCFD',
  'disabled-color-dark': '#FBFCFD',
  'zindex-message': '1070',
  'collapse-header-bg': '#FFFFFF',
  'collapse-header-padding': '9px 20px',
  'collapse-content-bg': '#FBFCFD',
  'collapse-content-padding': '16px 20px',
  'collapse-panel-border-radius': '0',
  'modal-mask-bg': 'rgba(25, 32, 44, 0.5)',
};

export default theme;
